server:
  port: 18001
  compression:
    enabled: true
spring:
  application:
    name: nekobot
  profiles:
    active: outer
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  aop:
    auto: true
    proxy-target-class: true
mybatis:
  mapper-locations: classpath:org.nekotori.dao/*.xml
  type-aliases-package: org.nekotori.entity

