server:
  port: 18001
  compression:
    enabled: true
spring:
  application:
    name: nekobot
  profiles:
    active: local
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  datasource:
    driver-class-name: org.sqlite.JDBC
  aop:
    auto: true
    proxy-target-class: true
logging:
  level:
    root: info
#mybatis:
#  mapper-locations: classpath:org.nekotori.dao/*.xml
#  type-aliases-package: org.nekotori.entity
img:
  loli-api: https://api.lolicon.app/setu
  yandere-post: https://yande.re/post.json
  yandere-tag: https://yande.re/tag.json
weather:
  location-api: https://geoapi.qweather.com/v2/city/lookup
  weather-api: https://devapi.qweather.com/v7/weather/3d
  #设备描述文件存储位置
bot:
  device-file: deviceInfo.json